name: Downloader from url

on:
  workflow_dispatch:
    inputs:
      mega_url:
        description: 'URL to download'
        required: true
      mega_file_name:
        description: 'The name of the file from url'
        required: true
      file_name:
        description: 'File Name that you want'
        required: true
      maximize_disk_space:
        description: Maximize disk space. Check if getting out of disk space error
        type: boolean

jobs:

  download:
    runs-on: ubuntu-latest
    
    steps:
    - name: Maximize disk space
      if: inputs.maximize_disk_space
      uses: easimon/maximize-build-space@v10
      with:
        remove-dotnet: true
        remove-android: true
        remove-haskell: true
        remove-codeql: true
        remove-docker-images: true
        
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y coreutils
        
    - name: Download from MEGA.nz
      run: |
        aria2c -x 16 -o "${{ inputs.mega_file_name }}" '${{ inputs.mega_url }}'
    
    - name: List files
      run: ls -l

    - name: Rename file
      run: |
        mv "${{ inputs.mega_file_name }}" "${{ inputs.file_name }}"

    - name: List files
      run: ls -l
        
    - name: Split file
      if: $(du -b "${{ inputs.file_name }}" | cut -f1) -gt 1000000000
      run: |
        split -b 1000m "${{ inputs.file_name }}" "${{ inputs.file_name }}."

    - name: List files
      run: ls -l
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.file_name }}.aa
        path: ${{ inputs.file_name }}.aa
        if-no-files-found: error
        retention-days: 5

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.file_name }}.ab
        path: ${{ inputs.file_name }}.ab
        if-no-files-found: error
        retention-days: 5
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.file_name }}.ac
        path: ${{ inputs.file_name }}.ac
        if-no-files-found: error
        retention-days: 5

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.file_name }}.ad
        path: ${{ inputs.file_name }}.ad
        if-no-files-found: error
        retention-days: 5

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.file_name }}.ae
        path: ${{ inputs.file_name }}.ae
        if-no-files-found: error
        retention-days: 5
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.file_name }}.af
        path: ${{ inputs.file_name }}.af
        if-no-files-found: error
        retention-days: 5