name: Download from MEGA.nz

on:
  workflow_dispatch:
    inputs:
      mega_urls:
        description: 'MEGA.nz URLs to download (up to 5, separated by commas or spaces)'
        required: true
      maximize_disk_space:
        description: Maximize disk space. Check if getting out of disk space error
        type: boolean

jobs:
  download:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Maximize disk space
      if: inputs.maximize_disk_space
      uses: easimon/maximize-build-space@v10
      with:
        remove-dotnet: true
        remove-android: true
        remove-haskell: true
        remove-codeql: true
        remove-docker-images: true
        
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install MEGAcmd
      run: |
        sudo apt-get update
        sudo apt-get install -y wget lsb-release
        UBUNTU_VERSION=$(lsb_release -rs)
        wget "https://mega.nz/linux/repo/xUbuntu_${UBUNTU_VERSION}/amd64/megacmd-xUbuntu_${UBUNTU_VERSION}_amd64.deb"
        sudo apt install -y "./megacmd-xUbuntu_${UBUNTU_VERSION}_amd64.deb"

    - name: Verify MEGAcmd installation
      run: mega-version
        
    - name: Download from MEGA.nz
      run: |
        # Replace commas with spaces, then split on spaces
        URLS=$(echo "${{ inputs.mega_urls }}" | tr ',' ' ')
        for url in $URLS; do
          mega-get "$url"
        done
    
    - name: List downloaded files
      run: ls -la

    - name: Sanitize, split, and upload files
      run: |
        shopt -s nullglob
        gh release create mega-downloads --title "mega-downloads" --notes "mega-downloads" || true
        for file in *; do
          if [[ -f "$file" && "$file" != "README.md" && "$file" != ".github" && "$file" != ".gitignore" ]]; then
            # Extract file extension
            extension="${file##*.}"
            # Generate a random file name
            random_name=$(uuidgen)
            # Combine the random name with the original file extension
            new_name="${random_name}.${extension}"

            # Check if the new name already exists in the GitHub release
            while gh release view mega-downloads --json assets --jq ".assets[].name" | grep -q "$new_name"; do
              random_name=$(uuidgen)
              new_name="${random_name}.${extension}"
            done

            # Check file size and split if larger than 2GB
            if [ $(stat -c%s "$file") -gt $((2 * 1024 * 1024 * 1024)) ]; then
              split -b 2G "$file" "${new_name}.part_"
              for part in ${new_name}.part_*; do
                echo "Uploading $part"
                gh release upload "mega-downloads" "./$part" --clobber
              done
            else
              # Rename the file
              mv "$file" "$new_name"
              # Upload the file
              echo "Uploading $new_name"
              gh release upload "mega-downloads" "./$new_name" --clobber
            fi
          fi
        done
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}

    - name: List files after processing
      run: ls -la
