name: Download from MEGA.nz

on:
  workflow_dispatch:
    inputs:
      mega_urls:
        description: 'MEGA.nz URLs to download (up to 5, separated by commas)'
        required: true
      maximize_disk_space:
        description: Maximize disk space. Check if getting out of disk space error
        type: boolean

jobs:
  download:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Maximize disk space
      if: inputs.maximize_disk_space
      uses: easimon/maximize-build-space@v10
      with:
        remove-dotnet: true
        remove-android: true
        remove-haskell: true
        remove-codeql: true
        remove-docker-images: true
        
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Determine Linux distribution
      id: distro
      run: |
        if [ -f /etc/os-release ]; then
          . /etc/os-release
          echo "id=$ID" >> $GITHUB_OUTPUT
          echo "version=$VERSION_ID" >> $GITHUB_OUTPUT
        else
          echo "id=unknown" >> $GITHUB_OUTPUT
          echo "version=unknown" >> $GITHUB_OUTPUT
        fi

    - name: Install MEGAcmd for Ubuntu
      if: steps.distro.outputs.id == 'ubuntu'
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget https://mega.nz/linux/MEGAsync/xUbuntu_${{ steps.distro.outputs.version }}/amd64/megacmd-xUbuntu_${{ steps.distro.outputs.version }}_amd64.deb
        sudo dpkg -i megacmd-xUbuntu_${{ steps.distro.outputs.version }}_amd64.deb

    - name: Install MEGAcmd for Debian
      if: steps.distro.outputs.id == 'debian'
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget https://mega.nz/linux/MEGAsync/Debian_${{ steps.distro.outputs.version }}/amd64/megacmd-Debian_${{ steps.distro.outputs.version }}_amd64.deb
        sudo dpkg -i megacmd-Debian_${{ steps.distro.outputs.version }}_amd64.deb

    - name: Install MEGAcmd for CentOS
      if: steps.distro.outputs.id == 'centos'
      run: |
        sudo yum install -y epel-release
        sudo yum install -y https://mega.nz/linux/MEGAsync/CentOS_${{ steps.distro.outputs.version }}/x86_64/megacmd-CentOS_${{ steps.distro.outputs.version }}.x86_64.rpm

    - name: Install MEGAcmd for Fedora
      if: steps.distro.outputs.id == 'fedora'
      run: |
        sudo dnf install -y https://mega.nz/linux/MEGAsync/Fedora_${{ steps.distro.outputs.version }}/x86_64/megacmd-Fedora_${{ steps.distro.outputs.version }}.x86_64.rpm

    - name: Verify MEGAcmd installation
      run: mega-version

    - name: Install additional dependencies
      run: |
        sudo apt-get install -y coreutils
        
    - name: Download from MEGA.nz
      run: |
        IFS=',' read -ra URLS <<< "${{ inputs.mega_urls }}"
        for url in "${URLS[@]}"; do
          mega-get "$url"
        done
    
    - name: List files
      run: ls -la

    - name: Process and upload files
      run: |
        shopt -s nullglob
        for file in *; do
          if [[ -f "$file" ]]; then
            filesize=$(stat -c%s "$file")
            if [ "$filesize" -gt 2000000000 ]; then
              split -b 2000m "$file" "${file}."
              for part in "${file}."*; do
                echo "Uploading $part"
                gh release upload "mega-downloads" "$part" --clobber
              done
              rm "$file"
            else
              echo "Uploading $file"
              gh release upload "mega-downloads" "./$file" --clobber
            fi
          fi
        done
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}

    - name: List files after processing
      run: ls -la
